#!/bin/bash
setxkbmap fi
alias gimme="sudo apt-get -y install"
alias lookfor="sudo apt search"
sudo apt-get update
sudo apt-get -y install git
sudo apt-get -y install puppet
git clone https://github.com/Tommi852/linux1.git
git config --global user.email "timonen@outlook.com"
git config --global user.name "Tommi Timonen"
git config --global credential.helper "cache --timeout=36000"
sudo cp -r linux1/puppet/. /etc/puppet/
sudo puppet apply --modulepath modules/ -e  'class {"ssh":}'
